name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]
    name: Lua ${{ matrix.luaVersion }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Run tests
        run: lua spec/test.lua
